package Vista;

import Controlador.clsPeliculas;
import Controlador.clsUsuarioConectado;
import Modelo.BitacoraDAO;
import Modelo.PeliculasDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class frmMantenimientoPeliculas2 extends javax.swing.JInternalFrame {
int idUsuario = Controlador.clsUsuarioConectado.getUsuId(); //este se mandó a llamar del clsUsuarioConectado

    PeliculasDAO peliculasDAO = new PeliculasDAO();
    
    

    public frmMantenimientoPeliculas2() {
        initComponents();
        llenadoDeTablas();
    }

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre Película");
        modelo.addColumn("Clasificación");
        modelo.addColumn("Género");
        modelo.addColumn("Subtitulado");
        modelo.addColumn("Idioma");
        modelo.addColumn("Precio");

        List<clsPeliculas> listaPeliculas = peliculasDAO.consultarPeliculas();
        String[] dato = new String[7];

        for (int i = 0; i < listaPeliculas.size(); i++) {
            dato[0] = Integer.toString(listaPeliculas.get(i).getIdPeliculas());
            dato[1] = listaPeliculas.get(i).getNombre();
            dato[2] = listaPeliculas.get(i).getClasificacion();
            dato[3] = listaPeliculas.get(i).getGenero();
            dato[4] = listaPeliculas.get(i).getSubtitulado();
            dato[5] = listaPeliculas.get(i).getIdioma();
            dato[6] = Double.toString(listaPeliculas.get(i).getPrecio());
            modelo.addRow(dato);
        }

        tablaPeliculas.setModel(modelo);
    }

    public void limpiarCampos() {
        nom.setText("");
        clan.setText("");
        gen.setText("");
        sub.setText("");
        idi.setText("");
        pre.setText("");
    }

    private void cargarFilaSeleccionada() {
        int fila = tablaPeliculas.getSelectedRow();
        if (fila >= 0) {
            nom.setText(tablaPeliculas.getValueAt(fila, 1).toString());
            clan.setText(tablaPeliculas.getValueAt(fila, 2).toString());
            gen.setText(tablaPeliculas.getValueAt(fila, 3).toString());
            sub.setText(tablaPeliculas.getValueAt(fila, 4).toString());
            idi.setText(tablaPeliculas.getValueAt(fila, 5).toString());
            pre.setText(tablaPeliculas.getValueAt(fila, 6).toString());
        }
    }

    private int obtenerIdSeleccionado() {
        int fila = tablaPeliculas.getSelectedRow();
        if (fila >= 0) {
            return Integer.parseInt(tablaPeliculas.getValueAt(fila, 0).toString());
        }
        return -1;
    }

    private void tablaPeliculasMouseClicked(java.awt.event.MouseEvent evt) {
        cargarFilaSeleccionada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        nom = new javax.swing.JTextField();
        clan = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        sub = new javax.swing.JTextField();
        idi = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        Insertar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiActionPerformed(evt);
            }
        });

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nombre", "clasificacion", "genero", "subtitulado", "idioma", "precio"
            }
        ));
        jScrollPane1.setViewportView(tablaPeliculas);

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        Modificar.setText("Modifcar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Clasificación:");

        jLabel4.setText("Genero:");

        jLabel5.setText("Subtitulado: ");

        jLabel6.setText("Idioma:");

        jLabel7.setText("Precio: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("CINEPOLIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(279, 279, 279)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Insertar)
                                .addGap(42, 42, 42)
                                .addComponent(Modificar)
                                .addGap(35, 35, 35)
                                .addComponent(Eliminar)
                                .addGap(33, 33, 33)
                                .addComponent(Buscar)))
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Insertar)
                            .addComponent(Modificar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buscar)
                            .addComponent(Eliminar))))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idiActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        // TODO add your handling code here:
         try {
            clsPeliculas pelicula = new clsPeliculas();
            pelicula.setNombre(nom.getText());
            pelicula.setClasificacion(clan.getText());
            pelicula.setGenero(gen.getText());
            pelicula.setSubtitulado(sub.getText());
            pelicula.setIdioma(idi.getText());
            pelicula.setPrecio(Double.parseDouble(pre.getText()));

            int resultado = peliculasDAO.ingresarPelicula(pelicula);

            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Insertado correctamente");
                int idUsuario = clsUsuarioConectado.getUsuId();
                int codigoAplicacion = 7;
                    BitacoraDAO bitacoradao = new BitacoraDAO();
                   
        bitacoradao.insert(idUsuario, codigoAplicacion, "INSERTAR");
                limpiarCampos();
                llenadoDeTablas();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al insertar");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Precio inválido");
        }
    
    }//GEN-LAST:event_InsertarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        try {
            int id = obtenerIdSeleccionado();

            if (id == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila");
                return;
            }

            clsPeliculas pelicula = new clsPeliculas();
            pelicula.setIdPeliculas(id);
            pelicula.setNombre(nom.getText());
            pelicula.setClasificacion(clan.getText());
            pelicula.setGenero(gen.getText());
            pelicula.setSubtitulado(sub.getText());
            pelicula.setIdioma(idi.getText());
            pelicula.setPrecio(Double.parseDouble(pre.getText()));

            int resultado = peliculasDAO.actualizarPelicula(pelicula);

            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Modificado correctamente");
                int idUsuario = clsUsuarioConectado.getUsuId();
                    BitacoraDAO bitacoradao = new BitacoraDAO();
                    int codigoAplicacion = 8;
        bitacoradao.insert(idUsuario, codigoAplicacion, "MODIFICAR");
                limpiarCampos();
                llenadoDeTablas();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al modificar");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Precio inválido");
        }
    
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
     int id = obtenerIdSeleccionado();

        if (id == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar?");
        if (confirm == 0) {
            clsPeliculas pelicula = new clsPeliculas();
            pelicula.setIdPeliculas(id);

            int resultado = peliculasDAO.borrarPelicula(pelicula);

            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Eliminado");
                int idUsuario = clsUsuarioConectado.getUsuId();
                    BitacoraDAO bitacoradao = new BitacoraDAO();
                    int codigoAplicacion = 9;
        bitacoradao.insert(idUsuario, codigoAplicacion, "Eliminar");
                limpiarCampos();
                llenadoDeTablas();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        }
    
    }//GEN-LAST:event_EliminarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        String texto = nom.getText().toLowerCase();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Clasificación");
        modelo.addColumn("Género");
        modelo.addColumn("Subtitulado");
        modelo.addColumn("Idioma");
        modelo.addColumn("Precio");

        List<clsPeliculas> lista = peliculasDAO.consultarPeliculas();
        String[] dato = new String[7];

        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getNombre().toLowerCase().contains(texto)) {
                dato[0] = String.valueOf(lista.get(i).getIdPeliculas());
                dato[1] = lista.get(i).getNombre();
                dato[2] = lista.get(i).getClasificacion();
                dato[3] = lista.get(i).getGenero();
                dato[4] = lista.get(i).getSubtitulado();
                dato[5] = lista.get(i).getIdioma();
                dato[6] = String.valueOf(lista.get(i).getPrecio());
                modelo.addRow(dato);
            }
        }
        
        BitacoraDAO bitacoradao = new BitacoraDAO();
                    int codigoAplicacion = 10;
        bitacoradao.insert(idUsuario, codigoAplicacion, "Eliminar");

        tablaPeliculas.setModel(modelo);
    
        
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPeliculas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPeliculas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPeliculas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoPeliculas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoPeliculas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField clan;
    private javax.swing.JTextField gen;
    private javax.swing.JTextField idi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pre;
    private javax.swing.JTextField sub;
    private javax.swing.JTable tablaPeliculas;
    // End of variables declaration//GEN-END:variables
}
